name: Run Tests

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: xdebug

      - uses: actions/checkout@v3

      - name: Install composer dependencies
        uses: ./.github/actions/composer-install

      - name: Execute unit and feature tests via PHP Unit
        run: php artisan test --coverage-clover=./coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          flags: unittests, featuretests
          fail_ci_if_error: true
          verbose: true
